// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Connect(arg1:types.ConnectionConfig):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<types.QueryResult>;

export function ExportData(arg1:types.QueryResult,arg2:string,arg3:string):Promise<void>;

export function GetColumns(arg1:string,arg2:string):Promise<Array<types.Column>>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetSavedConnections():Promise<Array<types.ConnectionConfig>>;

export function GetSchemas(arg1:string,arg2:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<types.Table>>;

export function RemoveConnection(arg1:string):Promise<void>;

export function SaveConnection(arg1:types.ConnectionConfig):Promise<void>;

export function TestConnection(arg1:types.ConnectionConfig):Promise<void>;
