// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginTransaction(arg1) {
  return window['go']['main']['App']['BeginTransaction'](arg1);
}

export function ClearQueryHistory() {
  return window['go']['main']['App']['ClearQueryHistory']();
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteQueryPaginated(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteQueryPaginated'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteQueryUnlimited(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQueryUnlimited'](arg1, arg2);
}

export function ExportData(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportData'](arg1, arg2, arg3);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function ExtractSQLVariables(arg1) {
  return window['go']['main']['App']['ExtractSQLVariables'](arg1);
}

export function GetColumns(arg1, arg2) {
  return window['go']['main']['App']['GetColumns'](arg1, arg2);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDefinition'](arg1, arg2, arg3);
}

export function GetFunctions(arg1, arg2) {
  return window['go']['main']['App']['GetFunctions'](arg1, arg2);
}

export function GetProcedures(arg1, arg2) {
  return window['go']['main']['App']['GetProcedures'](arg1, arg2);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetQueryHistory() {
  return window['go']['main']['App']['GetQueryHistory']();
}

export function GetQueryHistoryByConnection(arg1) {
  return window['go']['main']['App']['GetQueryHistoryByConnection'](arg1);
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetSchemas(arg1, arg2) {
  return window['go']['main']['App']['GetSchemas'](arg1, arg2);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTransactionMode(arg1) {
  return window['go']['main']['App']['GetTransactionMode'](arg1);
}

export function GetTriggers(arg1, arg2) {
  return window['go']['main']['App']['GetTriggers'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['main']['App']['GetViews'](arg1, arg2);
}

export function ImportProject(arg1) {
  return window['go']['main']['App']['ImportProject'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveSavedQuery(arg1) {
  return window['go']['main']['App']['RemoveSavedQuery'](arg1);
}

export function ReplaceSQLVariables(arg1, arg2) {
  return window['go']['main']['App']['ReplaceSQLVariables'](arg1, arg2);
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveSavedQuery(arg1) {
  return window['go']['main']['App']['SaveSavedQuery'](arg1);
}

export function SearchQueryHistory(arg1) {
  return window['go']['main']['App']['SearchQueryHistory'](arg1);
}

export function SetTransactionMode(arg1, arg2) {
  return window['go']['main']['App']['SetTransactionMode'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
