// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {sqlvariables} from '../models';
import {history} from '../models';

export function BeginTransaction(arg1:string):Promise<void>;

export function ClearQueryHistory():Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function Connect(arg1:types.ConnectionConfig):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<types.QueryResult>;

export function ExportData(arg1:types.QueryResult,arg2:string,arg3:string):Promise<void>;

export function ExtractSQLVariables(arg1:string):Promise<Array<sqlvariables.Variable>>;

export function GetColumns(arg1:string,arg2:string):Promise<Array<types.Column>>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetQueryHistory():Promise<Array<history.QueryEntry>>;

export function GetQueryHistoryByConnection(arg1:string):Promise<Array<history.QueryEntry>>;

export function GetSavedConnections():Promise<Array<types.ConnectionConfig>>;

export function GetSchemas(arg1:string,arg2:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<types.Table>>;

export function GetTransactionMode(arg1:string):Promise<string>;

export function RemoveConnection(arg1:string):Promise<void>;

export function ReplaceSQLVariables(arg1:string,arg2:Record<string, string>):Promise<string>;

export function Rollback(arg1:string):Promise<void>;

export function SaveConnection(arg1:types.ConnectionConfig):Promise<void>;

export function SearchQueryHistory(arg1:string):Promise<Array<history.QueryEntry>>;

export function SetTransactionMode(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:types.ConnectionConfig):Promise<void>;
